"""Write a per-material Unreal Python generator script from a JSON spec.

This script runs outside Unreal. The generated M_Name.py runs inside Unreal
Editor and creates or updates the material asset.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


MATERIAL_SCRIPT_TEMPLATE = r'''# Generated by UEMatGen. Run inside Unreal Editor Python.
from __future__ import annotations

import traceback

import unreal


SPEC = __SPEC_JSON__


MATERIAL_PROPERTIES = {
    "base_color": ("MP_BASE_COLOR", "MP_BaseColor"),
    "emissive": ("MP_EMISSIVE_COLOR", "MP_EmissiveColor"),
    "emissive_color": ("MP_EMISSIVE_COLOR", "MP_EmissiveColor"),
    "opacity": ("MP_OPACITY", "MP_Opacity"),
    "opacity_mask": ("MP_OPACITY_MASK", "MP_OpacityMask"),
    "roughness": ("MP_ROUGHNESS", "MP_Roughness"),
    "metallic": ("MP_METALLIC", "MP_Metallic"),
    "specular": ("MP_SPECULAR", "MP_Specular"),
    "normal": ("MP_NORMAL", "MP_Normal"),
    "world_position_offset": ("MP_WORLD_POSITION_OFFSET", "MP_WorldPositionOffset"),
}

BLEND_MODES = {
    "opaque": ("BLEND_OPAQUE",),
    "masked": ("BLEND_MASKED",),
    "translucent": ("BLEND_TRANSLUCENT",),
    "additive": ("BLEND_ADDITIVE",),
    "modulate": ("BLEND_MODULATE",),
}

SHADING_MODELS = {
    "default_lit": ("MSM_DEFAULT_LIT",),
    "unlit": ("MSM_UNLIT",),
    "subsurface": ("MSM_SUBSURFACE",),
    "preintegrated_skin": ("MSM_PREINTEGRATED_SKIN",),
    "clear_coat": ("MSM_CLEAR_COAT",),
    "two_sided_foliage": ("MSM_TWOSIDED_FOLIAGE",),
}

CUSTOM_OUTPUT_TYPES = {
    "float1": ("CMOT_FLOAT1", "CMOT_Float1"),
    "float2": ("CMOT_FLOAT2", "CMOT_Float2"),
    "float3": ("CMOT_FLOAT3", "CMOT_Float3"),
    "float4": ("CMOT_FLOAT4", "CMOT_Float4"),
}


def log(message):
    unreal.log("[UEMatGen] " + str(message))


def warn(message):
    unreal.log_warning("[UEMatGen] " + str(message))


def error(message):
    unreal.log_error("[UEMatGen] " + str(message))


def set_editor_property_if_possible(obj, property_name, value):
    try:
        obj.set_editor_property(property_name, value)
        return True
    except Exception:
        return False


def enum_value(enum_class_name, *names):
    enum_class = getattr(unreal, enum_class_name, None)
    if enum_class is None:
        return None
    for name in names:
        value = getattr(enum_class, name, None)
        if value is not None:
            return value
    return None


def material_property(key):
    names = MATERIAL_PROPERTIES.get(str(key).lower())
    if not names:
        raise ValueError("Unsupported material property: %s" % key)
    return enum_value("MaterialProperty", *names)


def split_asset_path(asset_path):
    if not asset_path.startswith("/Game/"):
        raise ValueError("asset_path must start with /Game/: %s" % asset_path)
    package_path, asset_name = asset_path.rsplit("/", 1)
    if not asset_name:
        raise ValueError("asset_path must include an asset name")
    return package_path, asset_name


def ensure_directory(package_path):
    if not unreal.EditorAssetLibrary.does_directory_exist(package_path):
        unreal.EditorAssetLibrary.make_directory(package_path)


def load_or_create_material(asset_path):
    package_path, asset_name = split_asset_path(asset_path)
    ensure_directory(package_path)

    existing = unreal.load_asset(asset_path)
    if existing:
        if not isinstance(existing, unreal.Material):
            raise TypeError("Existing asset is not a Material: %s" % asset_path)
        return existing

    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    material = asset_tools.create_asset(asset_name, package_path, unreal.Material, unreal.MaterialFactoryNew())
    if not material:
        raise RuntimeError("Failed to create material: %s" % asset_path)
    return material


def set_material_settings(material):
    blend_names = BLEND_MODES.get(str(SPEC.get("blend_mode", "opaque")).lower(), ("BLEND_OPAQUE",))
    blend_value = enum_value("BlendMode", *blend_names)
    if blend_value is not None:
        set_editor_property_if_possible(material, "blend_mode", blend_value)

    shading_names = SHADING_MODELS.get(str(SPEC.get("shading_model", "default_lit")).lower(), ("MSM_DEFAULT_LIT",))
    shading_value = enum_value("MaterialShadingModel", *shading_names)
    if shading_value is not None:
        set_editor_property_if_possible(material, "shading_model", shading_value)

    set_editor_property_if_possible(material, "two_sided", bool(SPEC.get("two_sided", False)))


def create_expression(material, expression_class_name, x, y):
    library = getattr(unreal, "MaterialEditingLibrary", None)
    creator = getattr(library, "create_material_expression", None) if library else None
    expression_class = getattr(unreal, expression_class_name, None)
    if not callable(creator) or expression_class is None:
        return None
    return creator(material, expression_class, x, y)


def create_scalar_parameter(material, name, default, x, y, group="UEMatGen"):
    node = create_expression(material, "MaterialExpressionScalarParameter", x, y)
    if node:
        set_editor_property_if_possible(node, "parameter_name", name)
        set_editor_property_if_possible(node, "default_value", float(default))
        set_editor_property_if_possible(node, "group", group)
        set_editor_property_if_possible(node, "desc", name)
    return node


def create_vector_parameter(material, name, default, x, y, group="UEMatGen"):
    values = list(default) + [1.0, 1.0, 1.0, 1.0]
    node = create_expression(material, "MaterialExpressionVectorParameter", x, y)
    if node:
        set_editor_property_if_possible(node, "parameter_name", name)
        set_editor_property_if_possible(
            node,
            "default_value",
            unreal.LinearColor(float(values[0]), float(values[1]), float(values[2]), float(values[3])),
        )
        set_editor_property_if_possible(node, "group", group)
        set_editor_property_if_possible(node, "desc", name)
    return node


def create_texture_sample_parameter(material, name, texture_path, x, y):
    node = create_expression(material, "MaterialExpressionTextureSampleParameter2D", x, y)
    if node:
        set_editor_property_if_possible(node, "parameter_name", name)
        set_editor_property_if_possible(node, "group", "Textures")
        set_editor_property_if_possible(node, "desc", name + " sampled color")
        if texture_path:
            texture = unreal.load_asset(texture_path)
            if not texture:
                warn("Texture asset not found for sampled parameter %s: %s" % (name, texture_path))
            else:
                set_editor_property_if_possible(node, "texture", texture)
    return node


def create_texture_object_parameter(material, name, texture_path, x, y):
    node = create_expression(material, "MaterialExpressionTextureObjectParameter", x, y)
    if node is None:
        node = create_expression(material, "MaterialExpressionTextureObject", x, y)
    if node:
        set_editor_property_if_possible(node, "parameter_name", name)
        set_editor_property_if_possible(node, "group", "Textures")
        set_editor_property_if_possible(node, "desc", name + " texture object")
        if texture_path:
            texture = unreal.load_asset(texture_path)
            if not texture:
                warn("Texture asset not found for texture object %s: %s" % (name, texture_path))
            else:
                set_editor_property_if_possible(node, "texture", texture)
    return node


def create_texture_coordinate(material, x, y):
    node = create_expression(material, "MaterialExpressionTextureCoordinate", x, y)
    if node:
        set_editor_property_if_possible(node, "desc", "UV")
        set_editor_property_if_possible(node, "coordinate_index", int(SPEC.get("uv_channel", 0)))
    return node


def create_time(material, x, y):
    node = create_expression(material, "MaterialExpressionTime", x, y)
    if node:
        set_editor_property_if_possible(node, "desc", "Time")
    return node


def create_constant(material, value, x, y):
    node = create_expression(material, "MaterialExpressionConstant", x, y)
    if node:
        set_editor_property_if_possible(node, "r", float(value))
    return node


def make_custom_input(input_name):
    for class_name in ("CustomInput", "MaterialExpressionCustomInput"):
        input_class = getattr(unreal, class_name, None)
        if input_class is None:
            continue

        constructed_with_name = False
        try:
            custom_input = input_class()
        except Exception:
            try:
                custom_input = input_class(input_name=input_name)
                constructed_with_name = True
            except Exception:
                continue

        if (
            set_editor_property_if_possible(custom_input, "input_name", input_name)
            or set_editor_property_if_possible(custom_input, "InputName", input_name)
            or set_editor_property_if_possible(custom_input, "inputName", input_name)
            or constructed_with_name
        ):
            return custom_input
    return None


def set_custom_inputs(custom, input_names):
    inputs = []
    for name in input_names:
        custom_input = make_custom_input(name)
        if custom_input:
            inputs.append(custom_input)
    if inputs:
        set_editor_property_if_possible(custom, "inputs", inputs)


def connect_material_expressions(from_expression, output_name, to_expression, input_names):
    library = getattr(unreal, "MaterialEditingLibrary", None)
    connector = getattr(library, "connect_material_expressions", None) if library else None
    if not callable(connector):
        return False

    output_names = output_name if isinstance(output_name, (tuple, list)) else (output_name,)
    target_inputs = input_names if isinstance(input_names, (tuple, list)) else (input_names,)
    for from_output_name in output_names:
        for input_name in target_inputs:
            try:
                if connector(from_expression, from_output_name, to_expression, input_name):
                    return True
            except Exception:
                pass
    return False


def connect_to_material(expression, output_name, property_key):
    property_value = material_property(property_key)
    if property_value is None:
        return False
    library = getattr(unreal, "MaterialEditingLibrary", None)
    connector = getattr(library, "connect_material_property", None) if library else None
    if not callable(connector):
        return False

    output_names = output_name if isinstance(output_name, (tuple, list)) else (output_name,)
    for from_output_name in output_names:
        try:
            if connector(expression, from_output_name, property_value):
                return True
        except Exception:
            pass
    return False


def create_custom_node(material, input_nodes):
    custom = create_expression(material, "MaterialExpressionCustom", 260, -140)
    if custom is None:
        raise RuntimeError("MaterialExpressionCustom is not available.")

    set_editor_property_if_possible(custom, "desc", SPEC.get("description", "UEMatGen Custom HLSL"))
    set_editor_property_if_possible(custom, "description", SPEC.get("description", "UEMatGen Custom HLSL"))
    set_editor_property_if_possible(custom, "code", SPEC["hlsl_code"])
    output_names = CUSTOM_OUTPUT_TYPES.get(str(SPEC.get("custom_output_type", "float3")).lower(), ("CMOT_FLOAT3", "CMOT_Float3"))
    output_value = enum_value("CustomMaterialOutputType", *output_names)
    if output_value is not None:
        set_editor_property_if_possible(custom, "output_type", output_value)

    set_custom_inputs(custom, list(input_nodes.keys()))
    failed = []
    for input_name, node_info in input_nodes.items():
        node = node_info["node"]
        source_output = node_info.get("output", "")
        if not connect_material_expressions(node, source_output, custom, (input_name,)):
            failed.append(input_name)
    if failed:
        warn("Could not connect Custom HLSL inputs: " + ", ".join(failed))
    return custom


def build_material(material):
    library = getattr(unreal, "MaterialEditingLibrary", None)
    if library and hasattr(library, "delete_all_material_expressions"):
        library.delete_all_material_expressions(material)

    input_nodes = {}
    y = -560

    if SPEC.get("include_uv", True):
        node = create_texture_coordinate(material, -900, y)
        if node:
            input_nodes[str(SPEC.get("uv_input_name", "UV"))] = {"node": node, "output": ""}
        y += 160

    if SPEC.get("include_time", True):
        node = create_time(material, -900, y)
        if node:
            input_nodes[str(SPEC.get("time_input_name", "Time"))] = {"node": node, "output": ""}
        y += 160

    for name, texture_path in (SPEC.get("texture_object_parameters") or {}).items():
        node = create_texture_object_parameter(material, name, texture_path, -900, y)
        if node:
            input_nodes[name] = {"node": node, "output": ""}
        y += 220

    for name, texture_path in (SPEC.get("texture_parameters") or {}).items():
        node = create_texture_sample_parameter(material, name, texture_path, -900, y)
        if node:
            input_nodes[name] = {"node": node, "output": "RGB"}
        y += 260

    for name, default in (SPEC.get("scalar_parameters") or {}).items():
        node = create_scalar_parameter(material, name, default, -560, y)
        if node:
            input_nodes[name] = {"node": node, "output": ""}
        y += 160

    for name, default in (SPEC.get("vector_parameters") or {}).items():
        node = create_vector_parameter(material, name, default, -560, y)
        if node:
            input_nodes[name] = {"node": node, "output": ""}
        y += 220

    custom = create_custom_node(material, input_nodes)
    if not connect_to_material(custom, ("", "Result"), SPEC.get("custom_output", "emissive")):
        warn("Could not connect Custom HLSL output to material property: " + str(SPEC.get("custom_output", "emissive")))

    x = 260
    y = 280
    for property_key, value in (SPEC.get("material_parameters") or {}).items():
        const = create_constant(material, value, x, y)
        if const and not connect_to_material(const, "", property_key):
            warn("Could not connect constant to material property: " + str(property_key))
        y += 150

    if library:
        if hasattr(library, "layout_material_expressions"):
            try:
                library.layout_material_expressions(material)
            except Exception:
                pass
        if hasattr(library, "recompile_material"):
            try:
                library.recompile_material(material)
            except Exception:
                pass

    try:
        material.post_edit_change()
    except Exception:
        pass


def main():
    try:
        asset_path = SPEC["asset_path"]
        material = load_or_create_material(asset_path)
        set_material_settings(material)
        build_material(material)
        unreal.EditorAssetLibrary.save_loaded_asset(material)
        log("Generated material asset: %s" % asset_path)
        return material
    except Exception:
        error("Failed to generate material.\n" + traceback.format_exc())
        raise


# Execute unconditionally so both -run=pythonscript and in-editor execution work.
main()
'''


def sanitize_asset_name(asset_path: str) -> str:
    name = asset_path.rstrip("/").rsplit("/", 1)[-1]
    if not name:
        raise ValueError("asset_path must include an asset name")
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not name.startswith("M_"):
        name = "M_" + name
    return name


def validate_spec(spec: dict) -> None:
    asset_path = spec.get("asset_path")
    if not isinstance(asset_path, str) or not asset_path.startswith("/Game/"):
        raise ValueError("spec.asset_path must be an Unreal package path starting with /Game/")
    asset_name = asset_path.rstrip("/").rsplit("/", 1)[-1]
    if not asset_name.startswith("M_"):
        raise ValueError("spec.asset_path asset name must start with M_")
    if "hlsl_code" not in spec or not str(spec["hlsl_code"]).strip():
        raise ValueError("spec.hlsl_code is required")


def write_material_script(spec: dict, out_dir: Path) -> Path:
    validate_spec(spec)
    out_dir.mkdir(parents=True, exist_ok=True)
    script_name = sanitize_asset_name(spec["asset_path"]) + ".py"
    script_path = out_dir / script_name
    rendered = MATERIAL_SCRIPT_TEMPLATE.replace(
        "__SPEC_JSON__",
        json.dumps(spec, indent=4, sort_keys=True),
    )
    script_path.write_text(rendered, encoding="utf-8", newline="\n")
    return script_path


def write_bat(script_path: Path, editor: str, uproject: str) -> Path:
    bat_path = script_path.with_name(script_path.stem + "_Run.bat")
    lines = [
        "@echo off",
        "\"%s\" ^" % editor,
        "  \"%s\" ^" % uproject,
        "  -run=pythonscript ^",
        "  -script=\"%s\" ^" % script_path,
        "  -unattended -nop4 -nosplash",
    ]
    bat_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\r\n")
    return bat_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write a UEMatGen per-material Unreal Python script.")
    parser.add_argument("spec", type=Path, help="Path to material spec JSON.")
    parser.add_argument("--out-dir", type=Path, required=True, help="Directory for generated M_Name.py.")
    parser.add_argument("--write-bat", action="store_true", help="Also write a Windows .bat launcher.")
    parser.add_argument("--editor", help="UnrealEditor-Cmd.exe path for the .bat file.")
    parser.add_argument("--uproject", help=".uproject path for the .bat file.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    script_path = write_material_script(spec, args.out_dir)
    print(script_path)
    if args.write_bat:
        if not args.editor or not args.uproject:
            raise ValueError("--write-bat requires --editor and --uproject")
        print(write_bat(script_path, args.editor, args.uproject))


if __name__ == "__main__":
    main()
